name: Review Dependabot PR

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  review_dependabot_pr:
    name: review_dependabot_pr
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Get Dependabot metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1

      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Approve patch and minor updates
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' || steps.dependabot-metadata.outputs.update-type == 'version-update:semver-minor' }}
        run: gh pr review $PR_URL --approve -b "✅ This Pull Request is auto **approved** because it includes a **patch or minor update**."
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Approve major updates of development dependencies
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major' && steps.dependabot-metadata.outputs.dependency-type == 'direct:development' }}
        run: gh pr review $PR_URL --approve -b "✅ This Pull Request is auto **approved** because it includes a **major update of a dev dependency**."
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Comment on major updates of non-development dependencies
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-major' && steps.dependabot-metadata.outputs.dependency-type == 'direct:production' }}
        run: |
          gh pr comment $PR_URL --body "❌ This Pull Request is **not auto approved** because it includes a **major update of a dependency** used in production."
          gh pr edit $PR_URL --add-label "requires-manual-approval"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
